### ISSUE TITLE
[Minor] No feature to go back on the plant matching quiz

### ISSUE THREAD

**Issue by RaphaelKyle** [info442-sp21/f-team#60] opened 2021-05-25 21:36 UTC
**Describe the bug**
When taking a quiz, there is no feature to go back when you accidentally misclicked something. If this is too hard to implement, maybe have a button to restart the quiz where the back button would be. 

**To Reproduce**
1. Go to the quiz icon

**Expected behavior**
A way to go back if I clicked the wrong thing. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.4)
 - Browser: Chrome 
 - Version: Version 91.0.4472.77 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sienasc** [comment] 2021-05-27 21:20
This issue is a duplicate of issue #58, which we ended up closing since this is not a feature we will be implementing.

**Closed by sienasc** 2021-05-27 21:20 UTC
Labels: bug, duplicate
