### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/f-team#77] opened 2021-06-03 19:47 UTC
**Describe the bug**
the quiz currently have an issue when a first time users interact with it they dont see a next button. 

**To Reproduce**
1. Go to the quiz at the top
2. Click on the quiz
3. Scroll down there isnt next button
4. See error cant move forward

**Expected behavior**
there should be a next button without zooming out.

**Screenshots**
![image](https://user-images.githubusercontent.com/43686537/120703170-d0e1c800-c469-11eb-9827-2de6a2ea7d83.png)

**Desktop (please complete the following information):**
 - Browser [ chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ndemmel** [comment] 2021-06-06 01:49
Duplicate of issue #56

**Closed by ndemmel** 2021-06-06 01:49 UTC
