### ISSUE TITLE
Feature Enhancement: Add a checklist feature

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/f-team#66] opened 2021-05-25 21:45 UTC
My suggested feature for this site is to ditch the different categories on the catalogue and add a checklist feature of all of these categories. This feature would be useful because it would allow users to see all plants that apply to multiple features. For example, users might want to see plants that need to be watered infrequently that is for a beginner.

**Comment by sienasc** [comment] 2021-05-27 21:28
This is a duplicate of issue #47.

**Closed by sienasc** 2021-05-27 21:28 UTC
Labels: duplicate, enhancement
